name: mirmachine
channels:
  - conda-forge
  - bioconda
dependencies:
  - appdirs =1.4.4
  - attrs =25.3.0
  - biopython =1.85
  - configargparse =1.7
  - datrie =0.8.2
  - docopt =0.6.2
  - docutils =0.21.2
  - gitdb =4.0.12
  - gitpython =3.1.44
  - jsonschema =4.23.0
  - nbformat =5.10.4
  - python-newick =1.10.0
  - numpy =2.2.5
  - psutil =7.0.0
  - pyyaml =6.0.2
  - smmap =5.0.2
  - snakemake-minimal =9.3.3
  - toposort =1.10
  - traitlets =5.14.3
  - wrapt =1.17.2
  - zipp =3.21.0
  - bedtools =2.31.1
  - gawk =5.3.1
  - samtools =1.21
  - infernal =1.1.5
  - moreutils =0.69
  - coreutils =9.5
  - rich =14.0.0
